промежуточный вариант, без работы вложенных
hamy11/clean-code pull request #1
Opened 2017-11-08 14:14 UTC by hamy11

2017-11-08 14:19 UTC, hamy11 commented
@tkirill

2017-11-12 16:54 UTC, tkirill requested changes

2017-11-12 16:54 UTC, tkirill commented on Markdown/Md.cs
> +            return currentTag.Definition == previousTag.Definition && currentTag.Type != previousTag.Type;
Почему пара ищется только на вершине стека?  Из-за этого не проходит такой тест: "__a _b c__" -> "<strong>a _b c</strong>".

2017-11-12 16:54 UTC, tkirill commented on Markdown/Md.cs
> +            return rules.All(rule => rule());
Есть проблема с незакрытыми тегами.  Сейчас так:

    "_a __b __c__ d_" -> "_a __b <strong>c</strong> d_"

2017-11-12 16:54 UTC, tkirill commented on Markdown/Spec.md
>  __Двумя символами__ — должен становиться жирным с помощью тега \<strong\>.
Зачем ты удалил половину спеки? 😨

2017-11-12 16:54 UTC, tkirill commented on Markdown/Tree.cs
> +    public interface IMatchType
Приписка "Type" лишняя, просто `IMatch`.  Пример из фреймворка: `InvalidOperationException` -> `Exception`.

2017-11-12 16:54 UTC, tkirill commented on Markdown/Tree.cs
> +    public class Tree //Aho-Corasick search tree
`Tree` -- слишком абстрактное название.  Это ведь конкретное дерево.

2017-11-12 16:54 UTC, tkirill commented on Markdown/Tree.cs
> +            node.Value = value;
`Node.Value` ведь нигде не используется?

2017-11-12 16:54 UTC, tkirill commented on Markdown/Tree.cs
> +        }
Что будет, если после `.Build` вызвать `.Add`?  Чтобы новое слово добавилось в автомат, достаточно снова позвать `.Build` или `.Build` нельзя звать ещё раз и нужно перестроить всё дерево?

Кажется, возможность менять дерево после постоения не нужна.  Можно было бы убрать публичный `.Add`, а все слова для автомата принимать в конструкторе.

2017-11-12 16:54 UTC, tkirill commented on Markdown/Tree.cs
> +    public class PatternMatch : IMatchType
Хорошая абстракция! 👍

2017-11-12 16:54 UTC, tkirill commented on Markdown/Tree.cs
> +        public IEnumerable<IMatchType> Find(string text)
`Tree` -- самостоятельный модуль.  На него нужны тесты.

2017-11-12 16:54 UTC, tkirill commented on Markdown/Md.cs
> +        private static bool CheckRules(Tag currentTag, Stack<Tag> noPairTagStack, string markdown)
У тебя получилось выделить [лексический анализ](https://ru.wikipedia.org/wiki/%D0%9B%D0%B5%D0%BA%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7) в отдельный модуль `Tree`.  Почему бы так же не выделить и [синтаксический анализ](https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7)?

Модуль синтаксического анализа инкапсюлировал бы грамматику языка и на выход отдавал уже готовые языковые единицы -- "символы".  Примеры символов:

* Tag -- тип тега и текст внутри тега
* Text -- просто строка

В твоём случае класс `Md` -- почти модуль синтаксического анализа, только обременённый лишней ответственностью по рендеру HTML.  Оставь ему роль синтаксического анализатора -- парсера -- а рендер вынеси в отдельный модуль.

Кстати, парсер можно сделать не только на `if`-ах, но и автоматом, [рекурсивным спуском](https://en.wikipedia.org/wiki/Recursive_descent_parser), [парсер-комбинаторами](https://ru.wikibooks.org/wiki/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%BF%D0%B0%D1%80%D1%81%D0%B5%D1%80%D1%8B) и ещё [кучей способов](https://en.wikipedia.org/wiki/Parsing).  Сейчас можно выбрать самый простой способ, но вдруг потом тебя заинтересует эта тема.

2017-11-12 16:59 UTC, tkirill commented on Markdown/Md.cs
> +            return htmlWriter.GetTagEntity(tagMatch.PatternValue, tagMatch.Position,
Тут смешиваются две ответственности: парсинг и генерация HTML.  Этот `Tag` потом используется в стеке при парсинге и по этому же тегу генерируется HTML.

Нужно разделить эти ответственности.  Ниже написал подробный комментарий про синтаксический анализ.

2017-11-12 19:33 UTC, hamy11 commented on Markdown/Tree.cs
> +        }
Добавление слова по сути это прирост недостающих состояний к дереву
А Build находит для всех вершин состояние неудачного перехода => будет работать если после Add сделать Build
Можно конечно убрать возможность перестраивать, но тогда диапазон применений данного дерева уменьшится

2017-11-13 09:14 UTC, tkirill commented on Markdown/Tree.cs
> +        }
Класс, тогда можно и оставить публичный `.Add`.

2017-11-13 23:14 UTC, hamy11 commented
@tkirill

2017-11-14 13:26 UTC, tkirill commented
@hamy11 LGTM!

2017-11-14 14:54 UTC, merged